// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCopxQPXS0krf5e9WtFRxM1SgbkQBhDdeY',
    appId: '1:80285202949:android:fc6b29f2ed4e59708cfa6c',
    messagingSenderId: '80285202949',
    projectId: 'flutterapps-f8045',
    databaseURL: 'https://flutterapps-f8045.firebaseio.com',
    storageBucket: 'flutterapps-f8045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqcWGQIFiKXJKvfrsKrE54mPSuZbbTyxI',
    appId: '1:80285202949:ios:d92918513a81a22c8cfa6c',
    messagingSenderId: '80285202949',
    projectId: 'flutterapps-f8045',
    databaseURL: 'https://flutterapps-f8045.firebaseio.com',
    storageBucket: 'flutterapps-f8045.appspot.com',
    iosClientId: '80285202949-6840ul3ntfnmgqmoospcjpc009p51iea.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPoc',
  );
}
